cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:product_id>/', views.cart_update, name='cart_update')
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

products/urls.py
from django.urls import path
from .import views

app_name = 'products'

urlpatterns = [
    path('<str:category_name>/', views.product_list, name='product_list_by_category'),
    path('<str:category_name>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<str:product_id>/<str:status_likes>/<str:model>', views.like_deslike_product, name='like_deslike_product'),
    path('<str:category_name>/<slug:slug>/<str:image>/', views.product_detail, name='product_detail_image'),
]

src/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('my-perfil/', include('perfil.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('cart/', include('cart.urls')),
    path('', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]
PRODUCT_QUANTITY_CHOICES_UPDATE = [(i, str(i)) for i in range(-1, -11, -1)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

class CartUpdateProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES_UPDATE, coerce=int)

cart/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from . cart import Cart
from . forms import CartAddProductForm, CartUpdateProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        print (cd)
        cart.add(product=product, quantity=cd['quantity'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@require_POST
def cart_update(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartUpdateProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.update(product=product, quantity=cd['quantity'])
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['add_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity']})
        item['update_quantity_form'] = CartUpdateProductForm(initial={'quantity': item['quantity']})
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load parcelas %}


{% block content %}

<h1>Your shopping cart</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Adicionar</th>
            <th>Diminuir</th>
            <th>Quantidade</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img
                        src="{% if product.image %}{{ product.image.url }} {% else %}{% static 'img/comp_estudante.png' %}{% endif %}">
                </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {% csrf_token %}
                    {{ item.add_quantity_form.quantity }}
                    <input type="submit" value="Add">
                </form>
            </td>
            <td>
                <form action="{% url 'cart:cart_update' product.id %}" method="post">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    <input type="submit" value="Update">
                </form>
            </td>
            <td>
                {{item.quantity}}
            </td>
            <td>
                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                    <input type="submit" value="Remove">
                    {% csrf_token %}
                </form>
            </td>
            <td>${{ item.price }}</td>
            <td>${{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'products:product_list_by_category' 'smartphone' %}" class="button light">Continue shopping</a>
</p>

<a href="{% url 'order:order_create' %}" class="button">
    Checkout
</a>

{% endblock %}