accounts/urls.py
from .import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register', views.register, name='register'),
    path('active/<uidb64>/<token>', views.register_email_confirm, name='register_email_confirm'),
    path('login/', views.login_user, name='login_user'),
    path('login/2fa/', views.login_twofa_authentication, name='login_twofa_authentication'),
    path('login/2fa/<str:resend_mail>', views.login_twofa_authentication, name='resend_login_twofa_authentication'),
    path('logout/', views.logout_user, name='logout_user'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/<uidb64>/<token>', views.password_reset_confirm, name='password_reset_confirm'),
    path('verification_email', views.verification_email, name='verification_email'),
]

src/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('my-perfil/', include('perfil.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('cart/', include('cart.urls')),
    path('', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.models import PermissionsMixin
from captcha.fields import ReCaptchaField

class User(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        'Usuário',
        max_length=150,
        unique=True,
        validators=[username_validator],
        error_messages={
            'unique': ("Esse usuário já existe, favor selecionar outro."),
        },
    )
    first_name = models.CharField('Nome', max_length=254)
    last_name = models.CharField('Sobrenome', max_length=254)
    email = models.EmailField(
        'E-mail',
        unique=True,         
        error_messages={
            'unique': ("Esse e-mail já existe, favor selecionar outro."),
        }
    )
    is_staff = models.BooleanField('É membro', default=False)
    is_active = models.BooleanField('É ativo', default=True)
    password_change = models.BooleanField(default=False)
    #verified = models.BooleanField(default=False, editable=False)
    verification_email = models.BooleanField('E-mail verificado', default=False)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    modified_at = models.DateTimeField('Modificado em', auto_now=True)
    deleted = models.BooleanField('Deletado', default=False)
    twofa = models.BooleanField('Autenticação em duas etapas', default=False)

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email',]

    objects = UserManager()

    class Meta:
        verbose_name = ('Usuário')
        verbose_name_plural = ('Usuários')
        ordering = ['first_name', 'last_name', ]

    def __str__(self):
        return f'{self.get_full_name()} {self.email}'

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def delete(self):
        self.deleted = True
        self.save()


class LoginCodeVerification(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)

    def __str__(self):
        return str(self.code)

accounts/forms.py
from .models import User, LoginCodeVerification
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from captcha.fields import ReCaptchaField, ReCaptchaV2Checkbox

class UserCreateForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', 
        widget=forms.PasswordInput(attrs={"class": "login-form-attr"}),
    )
    password2 = forms.CharField(label='Confirme a senha', 
        widget=forms.PasswordInput(attrs={"class": "login-form-attr"}),
    )
    #captcha = ReCaptchaField(label='', widget=ReCaptchaV2Checkbox(attrs={}))
    
    error_messages = {
        "password_mismatch": _("The two password fields didn’t match."),
        "password_small": _("A senha deve conter pelo menos 8 caracteres."),
        "email_exists": "E-mail fornecido já existe",
    }

    class Meta:
        model = User
        fields = ('first_name','last_name', 'email', 'password1', 'password2', 'twofa') #'captcha')
        widgets = {
            'first_name': forms.TextInput(attrs={"class": "login-form-attr"}),
            'last_name': forms.TextInput(attrs={"class": "login-form-attr"}),
            'email': forms.EmailInput(attrs={"class": "login-form-attr"}),
            'twofa': forms.CheckboxInput(attrs={"class": "login-form-attr"})
        }

    # def clean_username(self):
    #     cleaned_data = super().clean()
    #     username = cleaned_data.get("username")
    #     if 'ok' in username:
    #         raise ValidationError(
    #             "username testando xd"
    #         )
    #     return username

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        if len(password1) < 7 or len(password2) < 7:
            raise ValidationError(
                self.error_messages["password_small"],
                code="password_small",
            )
        if User.objects.filter(email__icontains=cleaned_data.get('email')).exists():
            raise ValidationError(
                self.error_messages["email_exists"],
                code="email_exists",
            )
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    email = forms.EmailField(label=_('E-mail'), max_length=200, required=True,
    widget=forms.TextInput(attrs={"class": "login-form-attr"})
    )
    password = forms.CharField(
        label=_("Senha"),
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "class":"login-form-attr"}),
    )

    #captcha = ReCaptchaField(label='', widget=ReCaptchaV2Checkbox(attrs={}))
    error_messages = {
        "invalid_login": _(
            "E-mail ou senha incorreto."
        ),
        "invalid_password": _ (
            "Faltou verificar o recaptcha."
        )
        #"inactive": _("This account is inactive."),
    }
    # def clean(self):
    #     cleaned_data = super().clean()
    #     username = cleaned_data.get("username")
    #     password = cleaned_data.get("password")
    #     if User.objects.filter(username__iexact=username):
    #         ok = User.objects.get(username__iexact=username)
    #         print (dir(ok))
    #         print (ok.set_password)
    #         msg = "Usuário ou senha incorreto"
    #         self.add_error('username', msg)
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("email")
        password = cleaned_data.get("password")
        # captcha = cleaned_data.get('captcha', """  """{})
        if not authenticate(username=username, password=password):
            raise ValidationError(
                self.error_messages["invalid_login"],
                code="inactive",
            )
        # if not captcha:
        #     raise ValidationError(
        #     self.error_messages["invalid_password"],
        #     code="inactive",
        #     )
        # return cleaned_data


class EmailToPasswordResetForm(forms.Form):
    email = forms.EmailField(
    label=_("Email"),
    max_length=254,
    widget=forms.EmailInput(attrs={"class": "login-form-attr"}),
)
    error_messages = {
        "invalid_email": _(
            "E-mail inserido inválido, tente novamente."
        ),
    }

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        if not User.objects.filter(email__iexact=email).exists():
            raise ValidationError(
                self.error_messages["invalid_email"],
                code="inactive",
            )
        return cleaned_data

class ResetPasswordForm(forms.Form):
    password1 = forms.CharField(label='Senha', 
        strip=False,
        widget=forms.PasswordInput(attrs={"class": "login-form-attr"}),
    )
    password2 = forms.CharField(label='Confirme a senha', 
        widget=forms.PasswordInput(attrs={"class": "login-form-attr"}),
        strip=False,
    )
    error_messages = {
        "invalid_password": _(
            "Senhas não são guais"
        ),
        "senha_pequena": _(
            "Senha menor que 8 caracteres"
        ),
    }
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 != password2:
            raise ValidationError(
                self.error_messages["invalid_password"],
                code="inactive",
            )
        if len(password1) < 8:
            raise ValidationError(
                self.error_messages["senha_pequena"],
                code="inactive",
            )
        
        return cleaned_data


class LoginCodeVerificationForm(forms.ModelForm):
    class Meta:
        model = LoginCodeVerification
        fields = ['code']
        widgets = {
            'code': forms.TextInput(),}
        labels = {
            "code": _("Código de segurança"),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class":"login-form-attr"})

    def clean(self):
        cleaned_data = super().clean()
        if 'a' == 8:
            raise ValidationError(
                self.error_messages["senha_pequena"],
                code="inactive",
            )
        self.add_error
        print (cleaned_data)
        return cleaned_data

accounts/views.py
from .models import User, LoginCodeVerification
from .forms import UserCreateForm, LoginForm, EmailToPasswordResetForm, ResetPasswordForm, LoginCodeVerificationForm
from .token import check_token_verified_email, generate_token_verified_email, password_reset_token, check_token_password_reset, generate_token_password_reset, login_code_authentication
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def login_user(request):
    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['email'], password=cd['password'])
            if user is not None and user.twofa:
                token_2fa = login_code_authentication(user, create=True)
                # PAREI AQUI, PEGA O TOKEN PARA ENVIAR O EMAIL
                #print (token_2fa)
                #login(request, user)
                #return redirect('perfil:my_perfil')
                return redirect('accounts:login_twofa_authentication')
            elif user is not None:
                request.session['user_pk'] = user.pk
                # request.session['fav_color'] = 'blue'
                # request.session['products'] = {'celular': '1'}
                # print (dir(request.session))
                # print ('*' * 50)
                login(request, user)
                if 'next' in request.META['HTTP_REFERER']:
                    return redirect(request.META['HTTP_REFERER'].split('next=')[1])

                return redirect ('perfil:my_perfil')

    return render(request, 'accounts/login.html', {'login_form': login_form})

def login_twofa_authentication(request, resend_mail=None):
    if resend_mail:
        user_pk = request.session.get('user_pk')
        user = get_object_or_404(User, pk=user_pk)
        login_code_authentication(user, create=True)
        return redirect('accounts:login_twofa_authentication')
    login_code_form = LoginCodeVerificationForm()
    if request.method == 'POST':
        login_code_form = LoginCodeVerificationForm(request.POST)
        if login_code_form.is_valid():
            user_pk = request.session.get('user_pk')
            user = get_object_or_404(User, pk=user_pk)
            cd = login_code_form.cleaned_data
            try:
                if user.logincodeverification.code == cd['code']:
                    login(request, user, backend='accounts.backends.EmailBackend')
                    login_code_authentication(user, delete=True)
                    return redirect('core:index')
                else:
                    login_code_form.add_error(None, "Código de segurança inválido.")
                    return render(request, 'accounts/login_2fa.html', {'login_code_form': login_code_form})
            except Exception:
                #.add_error(None, 'TEXT') adiciona erro no def non_field_errors do form
                login_code_form.add_error(None, "Código de segurança inválido")
                return render(request, 'accounts/login_2fa.html', {'login_code_form': login_code_form})

    return render(request, 'accounts/login_2fa.html', {'login_code_form': login_code_form})

def logout_user(request):
    logout(request)
    return redirect('accounts:login_user')

def verification_email(request):
    if 'accounts/profile/' in request.META.get('HTTP_REFERER', {}):
        user = request.user
        to_email = user.email
        if not request.user.verification_email:
            generate_token_verified_email(request, user, to_email)
        return render(request, 'accounts/verification_email.html')
    else:
        return render(request, 'error404.html')

def register(request):
    user_form = UserCreateForm()

    if request.method == 'POST':
        user_form = UserCreateForm(request.POST)
        if user_form.is_valid():
            cd = user_form.cleaned_data
            user = user_form.save()
            generate_token_verified_email(request, user, cd['email'])
            return render(request, 'accounts/register_sucess.html')
        else:
            user_form = UserCreateForm(request.POST)
    return render(request, 'accounts/register.html', {'user_form': user_form})

def register_email_confirm(request, uidb64, token):
    check_token = check_token_verified_email(uidb64, token)
    if check_token:
        return render(request, 'accounts/register_email_confirm_sucess.html')
    else:
        return render(request, 'accounts/register_email_confirm_error.html')


#FORGET PASSWORD
def password_reset(request):
    password_reset_form = EmailToPasswordResetForm()
    if request.method == 'POST':
        password_reset_form = EmailToPasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            to_email = password_reset_form.cleaned_data
            user = User.objects.get(email=to_email['email'])
            generate_token_password_reset(request, user, to_email['email'])
            return render(request, 'accounts/password_reset_done.html')
    return render(request, 'accounts/password_reset.html', {'password_reset_form': password_reset_form})

def password_reset_confirm(request, uidb64, token):
    reset_password_form = ResetPasswordForm()
    
    uid = force_str(urlsafe_base64_decode(uidb64))
    user = User.objects.get(pk=uid)
    check_token = password_reset_token.check_token(user, token)

    if check_token:
        if request.method == 'POST':
            reset_password_form = ResetPasswordForm(request.POST)
            if reset_password_form.is_valid():
                cd = reset_password_form.cleaned_data
                check_token = check_token_password_reset(uidb64, token, cd['password1'])
                if check_token:
                    #user = User.objects.filter(username=check_token)
                    return render(request, 'accounts/password_reset_confirm_sucess.html')
                else:
                    return render(request, 'accounts/password_reset_confirm_error.html')
        return render(request, 'accounts/password_reset_form.html',{'reset_password_form': reset_password_form, 'uidb64': uidb64, 'token': token})  
    else:
        return render(request, 'accounts/password_reset_confirm_error.html')

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="login-register-form-container">
    <div class="form-login-content">
        <div class="form-login-items">
            <form method="post" action="{% url 'accounts:login_user' %}">
                {% csrf_token %}

                <div>
                    <h2>Já possui cadastro em nosso site?</h2>
                    <h3>Entre em nosso site e aproveite os mais diversos produtos disponíveis</h3>
                </div>
                {{ login_form.non_field_errors }}
                {% for field in login_form %}
                <div class="form-login-items-labelinput">
                    <div class="form-login-items-labelinput-label">
                        {{field.label}} {% if field.label != '' %} <span>*</span> {% endif %}
                    </div>
                    <div>
                        {{field}}
                    </div>
                </div>
                {% endfor %}
                <a href="{% url 'accounts:password_reset' %}">Esqueceu a senha?</a>
                <button type="submit" value="Submit"> Continuar </button>
            </form>
        </div>
        <div id="linha-vertical"></div>
        <div class="form-login-items-register">
            <div>
                <h2>Não possui conta em nosso site?</h2>
                <p>Registre-se agora e obtenha muito mais vantagens</p>
            </div>
            <ul>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>Diversos produtos a sua escolha</span></li>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>Fácil de buscar e comprar</span></li>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>Descontos exclusivos para usuários</span></li>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>Segurança na hora do pagamento</span></li>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>O único e-commerce completo</span></li>
            </ul>
            <a href="{% url 'accounts:register' %}"><button>Registre-se</button></a>
        </div>

    </div>



</div>
{% endblock %}

<form action="">
    {% csrf_token %}
    {{login_form.as_p}}
</form>

templates/accounts/login_2fa.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login {% endblock %}

{% block content %}

<form method="post" action="{% url 'accounts:login_twofa_authentication' %}">
    {% csrf_token %}
    {{ login_code_form.non_field_errors }}
    {% for field in login_code_form %}
    <div class="form-login-items-labelinput">
        <div class="form-login-items-labelinput-label">
            {{field.label}} {% if field.label != '' %} <span>*</span> {% endif %}
        </div>
        <div>
            {{field}}
        </div>
    </div>
    {% endfor %}
    <button type="submit" value="Submit"> Continuar </button>
</form>

<a href="{% url 'accounts:resend_login_twofa_authentication' True %}">Reenviar código de segurança?</a>
{% endblock %}

<form action="">
    {% csrf_token %}
    {{login_form.as_p}}
</form>

templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Register confirm sucess {% endblock %}

{% block content %}

<div class="password_reset_container">
    <div class="password_reset_content">
        <div>
            <h2>Recuperar a senha</h2>
            <h3>Para redefinir sua senha, ensira o e-mail que você cadastrou.</h3>
            <h3>O link será enviado ao seu e-mail. Por favor, checar a caixa de entrada e spam.</h3>
        </div>
        <div class="password_reset_item-form">
            <form method="post" action="{% url 'accounts:password_reset' %}">
            {% csrf_token %}
            {{ password_reset_form.non_field_errors }}
            {% for field in password_reset_form %}
            <div class="form-login-items-labelinput">
                <div class="form-login-items-labelinput-label">
                    {{field.label}} {% if field.label != '' %} <span>*</span> {% endif %}
                </div>
                <div>
                    {{field}}
                </div>
            </div>
            {% endfor %}
            <button type="submit" value="Submit"> Enviar </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/password_reset_confirm.html
TROCAR DE SENHA
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

templates/accounts/password_reset_confirm_sucess.html
<h1>FOI SALVO COM SUCESSO</h1>

templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Passord reset done {% endblock %}

{% block content %}
    <div class="password-reset-done">
        <h1>Para concluir a recuperação de senha, verifique seu e-mail.</h1>
        <h2>Lembrando que o link é válido por 24 horas ou a realização de uma troca de senha, ok?</h2>
        <a href="{% url 'accounts:login_user' %}"> <h2>Fazer login? </h2></a>
    </div>
{% endblock %}

templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% autoescape off %}

{% block title %} Register confirm sucess {% endblock %}

{% block content %}

<div class="reset-form-container">
    <div class="reset-form-content">
        <div class="reset-form-items-descricao">
            <ul>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>Escolha uma senha forte</span></li>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>Não compartilhe com ninguém a sua senha</span></li>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>Caso se esqueça, não tem problema!</span></li>
                <li><i class="fa-duotone fa-check fa-2x"></i><span>Recuperamos a senha para vocẽ!</span></li>
            </ul>
        </div>
        <div class="reset-form-items-form">
            <form method="post" action="{% url 'accounts:password_reset_confirm' uidb64=uidb64 token=token %}">
                {% csrf_token %}
                {{ reset_password_form.non_field_errors }}
                {% for field in reset_password_form %}
                <div class="form-login-items-labelinput">
                    <div class="form-login-items-labelinput-label">
                        {{field.label}} {% if field.label != '' %} <span>*</span> {% endif %}
                    </div>
                    <div>
                        {{field}}
                    </div>
                </div>
                {% endfor %}
                <button type="submit" value="Submit"> Salvar </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% endautoescape %}

templates/accounts/profile_user.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Profile User {% endblock %}

{% block content %}
    
    {{user_form}}

    {% if not request.user.verification_email %}
    <h5>e-mail não verificado, verifique seu e-mail para obter melhor experiência em nosso site. <a href="{% url 'accounts:verification_email' %}">Enviar link?</a></h5>
    {% endif %}
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Register {% endblock %}

{% block content %}
<div class="form-register-container">
    <div class="form-register-content">
        <div class="form-register-items-img">
            <img src="{% static 'img/python-application.png' %}" alt="" style="height: 100%;">
        </div>
        <div class="form-register-items-formregister">
            <form method="post" action="{% url 'accounts:register' %}">
                {% csrf_token %}
                {{ user_form.non_field_errors }}
                {% for field in user_form %}
                <div class="form-login-items-labelinput">
                    <div class="form-login-items-labelinput-label">
                        {{field.label}} {% if field.label != '' %} <span>*</span> {% endif %}
                    </div>
                    <div>
                        {{field}}
                    </div>
                </div>
                {% endfor %}
                <button type="submit" value="Submit"> Continuar </button>
            </form>
        </div>
    </div>
</div>

<a href="{% url 'accounts:logout_user' %}"> LOGOUT KKKKKKKKKKK</a>

{% endblock %}



<!-- <form method="post" action="{% url 'accounts:register' %}">
    {% csrf_token %}
    {% for field in user_form %}
    <div>
        {{field.label}}
    </div>
    <div>
        <div class="inputlist">
            {{field}}
        </div>
        {% for error in field.errors %}
        <div> 
            <span class="errorlist">{{error}}</span> 
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" value="Submit"> Continuar </button>
</form>

<a href="{% url 'accounts:logout_user' %}"> LOGOUT KKKKKKKKKKK</a> -->

templates/accounts/register_email_confirm.html
Confirm e-mail valid:
{{ protocol}}://{{ domain }}{% url 'accounts:register_email_confirm' uidb64=uid token=token %}

templates/accounts/register_email_confirm_error.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Register ERROR {% endblock %}

{% block content %}
    <h1>Seu e-mail já foi ativado. Este link está invalido.</h1>

{% endblock %}

templates/accounts/register_email_confirm_sucess.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Register confirm sucess {% endblock %}

{% block content %}
    <h1>PARABÉNS, E-MAIL VERIFICADO COM SUCESSO</h1>

{% endblock %}

templates/accounts/register_sucess.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Register sucess {% endblock %}

{% block content %}
    <h1>PARABÉNS, SUA CONTA FOI CRIADA COM SUCESSO. PARA USUFRUIR DOS DEMAIS SERVIÇOS, VERIFIQUE SEU E-MAIL COM UM LINK QUE ENVIAMOS.'</h1>

{% endblock %}

templates/accounts/verification_email.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Verification Email {% endblock %}

{% block content %}
    <h1>Reenviamos um link de ativação ao seu e-mail, verifique sua caixa de entrada e spam</h1>
{% endblock %}