cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:product_id>/', views.cart_update, name='cart_update')
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index')
]

products/urls.py
from django.urls import path
from .import views

app_name = 'products'

urlpatterns = [
    path('<str:category_name>/', views.product_list, name='product_list_by_category'),
    path('<str:category_name>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<str:product_id>/<str:status_likes>/<str:model>', views.like_deslike_product, name='like_deslike_product'),
    path('<str:category_name>/<slug:slug>/<str:image>/', views.product_detail, name='product_detail_image'),
]

src/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('my-perfil/', include('perfil.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('cart/', include('cart.urls')),
    path('', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User
from django.template.defaultfilters import slugify
from django.conf import settings
from tinymce.models import HTMLField


class Brand(models.Model):
    name = models.CharField(max_length=20, db_index=True)
    slug = models.SlugField(max_length=20, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'brand'
        verbose_name_plural = 'brands'
    
    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('products:product_list_by_category', args=[self.slug])

class Category(models.Model):
    name = models.CharField(max_length=30, db_index=True)
    slug = models.SlugField(max_length=30, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('products:product_list_by_category', args=[self.slug])

class Image(models.Model):
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    def __str__ (self):
        return self.image.url

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, related_name='brand', on_delete=models.CASCADE)
    image = models.ManyToManyField(Image, blank=True)
    like = models.ManyToManyField(User, blank=True, related_name='like')
    deslike = models.ManyToManyField(User, blank=True, related_name='deslike')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = HTMLField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        
    def __str__(self):
        return f'{self.category} {self.brand} {self.name}'

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.category, self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.brand.name} {self.name}')
        super().save(*args, **kwargs)
        
class Comment(models.Model):
    product = models.ForeignKey(Product, related_name='comment', on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE, blank=True, null=True)
    body = models.TextField(default='', max_length=600)
    like = models.ManyToManyField(User, blank=True, related_name='like_comment')
    deslike = models.ManyToManyField(User, blank=True, related_name='deslike_comment')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.user} on {self.product}'

products/forms.py
from distutils.command.clean import clean
from django.contrib.auth import authenticate, password_validation
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import User, Comment
#from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from .models import Product

class SearchForm(forms.Form):
    search = forms.CharField(max_length=300)

class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['like', 'deslike']

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.TextInput(attrs={"class": "comment-form-attr"}),
        }
        labels = {
            'body': 'comentar'
        }

products/views.py
from .models import Category, Product, Image, User, Comment
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from products.utils import pagination
from .forms import ProductModelForm, CommentModelForm
from cart.forms import CartAddProductForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
#from django.db import connection, reset_queries

def product_list(request, category_name=None):
    category = None
    products = Product.objects.filter(available=True)

    if category_name:
        category = get_object_or_404(Category, name=category_name.lower())
        products = Product.objects.filter(category=category).filter(available=True).select_related('category').select_related('brand')
    
    page_obj = pagination(request, products, 3)

    return render(request, 
                'products/list.html',
                {'category': category,
                'page_obj': page_obj,
            })

def product_detail(request, category_name, slug, image=None):
    #Produto selecionado no template list products
    product = get_object_or_404(Product, slug__iexact=slug, available=True)
    cart_product_form = CartAddProductForm()
    #Commentários
    comment_form = CommentModelForm()
    #Desabilita o botão de submit se o usuário logado já comentou no product
    button_status = None
    #Desabilita o comentário se o user já comentou neste produto.
    # if product.comment.filter(user=request.user).exists():
    #     button_status = True
    #     for field in comment_form:
    #         field.field.widget.attrs.update({"class": "comment-form-attr-block", "readonly": True, "placeholder": "Você já comentou este produto"})

    #Primeira imagem a aparecer do produto
    image_first = product.image.first()

    #Alguma imagem selecionada
    image_selected = None
    if image:
        image_selected = product.image.get(id=image)

    #Pagination images
    page_images = pagination(request, product.image.all().order_by('id'), 4)

    if request.method == 'POST':
        if not request.user.is_authenticated:
            print (request.path)
            return redirect(f'/accounts/login/?next={request.path}')
            #return render(request, 'accounts/login.html')
        # if product.comment.filter(user=request.user).exists():
        #     comment_form = CommentModelForm()
        #     button_status = True
        #     for field in comment_form:
        #         field.field.widget.attrs.update({"class": "comment-form-attr-block", "readonly": True, "placeholder": "Você já comentou este produto" })
        else:
            comment_form = CommentModelForm(data=request.POST)
            if comment_form.is_valid():
                save_comment_form = comment_form.save(commit=False)

                #Salvando as informações essenciais pro comentário aparecer
                save_comment_form.user = request.user
                save_comment_form.product = product
                save_comment_form.save()

                comment_form = CommentModelForm()
                button_status = True
                for field in comment_form:
                    field.field.widget.attrs.update({"class": "comment-form-attr-block", "readonly": True, "placeholder": "Você já comentou este produto" })


    return render(request, 
                'products/detail_item.html', 
                {
                    'product': product,
                    'image_selected': image_selected,
                    'image_first': image_first,
                    'page_images': page_images,
                    'comment_form': comment_form,
                    'button_status': button_status,
                    'cart_product_form': cart_product_form
                }
            )

@login_required()
@require_POST
def like_deslike_product(request, product_id=None, status_likes=None, model=None):
    #product.like.remove(request.user)
    if model.lower() == 'product':
        product = get_object_or_404(Product, id=product_id)
        if status_likes == 'like':
            product.like.remove(request.user.id) if product.like.filter(id=request.user.id).exists() else product.like.add(request.user)

        if status_likes == 'deslike':
            product.deslike.remove(request.user.id) if product.deslike.filter(id=request.user.id).exists() else product.deslike.add(request.user)

        return redirect (request.META['HTTP_REFERER'])

    if model.lower() == 'comment':
        comment = get_object_or_404(Comment, id=product_id)
        if status_likes == 'like':
            comment.like.remove(request.user.id) if comment.like.filter(id=request.user.id).exists() else comment.like.add(request.user)

        if status_likes == 'deslike':
            comment.deslike.remove(request.user.id) if comment.deslike.filter(id=request.user.id).exists() else comment.deslike.add(request.user)

        return redirect (request.META['HTTP_REFERER'])

templates/products/detail_item.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load parcelas %}


{% block title %} detail-product {% endblock %}

{% block content %}

<!-- <div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url 'core:index' %}">All</a>
        </li>
    </ul>
</div> -->
<!--
    TODO PAGINAÇÃO DOS ITEMS
-->

<div class="product-detail-container">
    <div class="product-detail-content">
        <h1>{{product|capfirst}}</h1>
        <div class="product-detail-content-images">
            <div class="product-detail-items-images-group">
                <div class="product-detail-item-images">
                    {% for image in page_images %}
                    <a href="{% url 'products:product_detail_image' product.category product.slug image.id%}">
                        <img src="{{image}}" alt="test" {% if image == image_selected %} style="border: 3px solid #61a5bf;" {% endif %}>
                    </a>
                    {% endfor %}
                    <!-- PAGINATION NEXT -->
                    {% if page_images.has_next %}
                        <a href="?page={{ page_images.next_page_number }}"><i class="fa-duotone fa-forward"></i></a>
                    {% endif %}

                    <!-- PAGINATION PREVIOUS -->
                    {% if page_images.has_previous %}
                        <a href="?page={{ page_images.previous_page_number }}"><i class="fa-solid fa-backward"></i></a>
                    {% endif %}
                </div>
                <div class="product-detail-item-image-first">
                    <img src="{% if image_selected %} {{image_selected}} {% else %} {{image_first}} {% endif %}" alt="test">
                </div>
            </div>
            <div class="product-detail-item-atributes">
                <div>
                    <h2>R${{product.price|intcomma}}</h2>
                    <h3>Em até 10x de R$ {{product.price|parcelas:"10"|intcomma}}</h3>
                </div>
                <div>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <input type="submit" value="Add to cart">
                    </form>
                </div>
                <div class="product-detail-item-atributes-like">
                    <div>
                        <form method="post" action="{% url 'products:like_deslike_product' product.id 'like' 'product' %}">
                            {% csrf_token %}
                            <button type="submit"> {% if request.user in product.like.all %} <i class="fa-solid fa-thumbs-up fa-4x"></i> {% else %}
                                <i class="fa-regular fa-thumbs-up fa-4x"></i> {% endif %} </button>
                        </form>
                        <h3 style="margin: 0 auto;">{{product.like.count}}</h3>
                    </div>
                    <div>
                        <form method="post" action="{% url 'products:like_deslike_product' product.id 'deslike' 'product' %}">
                            {% csrf_token %}
                            <button type="submit">{% if request.user in product.deslike.all %} <i class="fa-solid fa-thumbs-down fa-4x"></i> {% else %} 
                                <i class="fa-regular fa-thumbs-down fa-4x"></i> {% endif %}</button>
                            <button type="submit"></button>
                        </form>
                        <h3>{{product.deslike.count}}</h3>
                    </div>
                </div>
            </div>   
        </div>
        <div class="product-detail-content-description">
            <h2>Descrição</h2>
            {% autoescape off %}
                {{product.description}}
            {% endautoescape %}
        </div>
        <div class="product-detail-content-comments">
            {% with total_comments=product.comment.all.count %}
                <h2>{{ total_comments }} Comentário{{ total_comments|pluralize }}</h2>
            {% endwith %}
            {% for comment in product.comment.all %}
                <div class="product-detail-items-comments">
                    <div class="product-detail-items-name-created">
                        <h3>{{comment.user.get_full_name|capfirst}}</h3>
                        <div class="product-detail-items-created-likes">
                            <h5>{{comment.created}}</h5>
                            <form method="post" action="{% url 'products:like_deslike_product' comment.id 'like' 'comment' %}" style="margin: 0px 20px;">
                                {% csrf_token %}
                                <button type="submit"> {% if request.user in comment.like.all %} <i class="fa-solid fa-thumbs-up fa-2x"></i> {% else %}
                                    <i class="fa-regular fa-thumbs-up fa-2x"></i> {% endif %} 
                                </button>
                                <h3 style="margin: 0 auto;">{{comment.like.count}}</h3>
                            </form>
                            <form method="post" action="{% url 'products:like_deslike_product' comment.id 'deslike' 'comment' %}">
                                {% csrf_token %}
                                <button type="submit">{% if request.user in comment.deslike.all %} <i class="fa-solid fa-thumbs-down fa-2x"></i> {% else %} 
                                    <i class="fa-regular fa-thumbs-down fa-2x"></i> {% endif %}
                                </button>
                                <h3>{{comment.deslike.count}}</h3>
                            </form>
                        </div>
                    </div>
                    <p>{{comment.body|capfirst}}</p>
                </div>
            {% endfor %}

            <hr style="margin-bottom: 20px;">

            <div class="product-detail-items-comment-form">
                <form method="post" action="">
                    {% csrf_token %}
                    {% for field in comment_form %}
                        {{field.label|capfirst}}:
                        {{field}}
                    {% endfor %}
                        
                      <button {% if button_status %} disabled {% else %} None {% endif %} type="submit"> Comentar </button>
                </form> 
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/products/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} index {% endblock %}

{% block content %}

<!-- <div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url 'core:index' %}">All</a>
        </li>
    </ul>
</div> -->
<!--
    TODO PAGINAÇÃO DOS ITEMS
-->
<div id="main" class="product-list-container">
    <h1>{% if category %}{{ category.name|capfirst }}{% else %}Products{% endif %}</h1>
    <div class="product-list-content">
        <!-- PAGINATION PREVIOUS -->
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-backward"></i></a>
        {% endif %}

        <!--ITEMS-->
        {% for obj in page_obj %}
        <a href="{{ obj.get_absolute_url }}">
            <div class="product-list-item">
                <div class="product-list-item-img">
                    <img src="{% if obj.image %}{{ obj.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
                </div>
                <div class="product-list-item-description">
                    <h3>{{ obj|truncatechars:70 }}</h3>
                    <br>
                    <h3>R$ {{ obj.price }}</h3>
                </div>
            </div>
        </a>
        {% endfor %}
        <!-- PAGINATION NEXT -->
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"><i class="fa-duotone fa-forward"></i></a>
        {% endif %}
    </div>
</div>

{% endblock %}