accounts/urls.py
from .import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register', views.register, name='register'),
    path('active/<uidb64>/<token>', views.register_email_confirm, name='register_email_confirm'),
    path('login/', views.login_user, name='login_user'),
    path('login/2fa/', views.login_twofa_authentication, name='login_twofa_authentication'),
    path('login/2fa/<str:resend_mail>', views.login_twofa_authentication, name='resend_login_twofa_authentication'),
    path('logout/', views.logout_user, name='logout_user'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset/<uidb64>/<token>', views.password_reset_confirm, name='password_reset_confirm'),
    path('verification_email', views.verification_email, name='verification_email'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:product_id>/', views.cart_update, name='cart_update')
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index')
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.my_perfil, name='my_perfil'),
    path('<str:fk>', views.my_perfil, name='my_perfil_foreignkey'),
]

src/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('my-perfil/', include('perfil.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('cart/', include('cart.urls')),
    path('', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/stylee.css' %}">
    <script src="https://kit.fontawesome.com/53c22141b9.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/python.png' %}"/>
    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
</head>

<body>
    <header>
        <div class="header-container">
            <div class="header-content">
                <div class="header-item-logo">
                    <a href="{% url 'core:index' %}"><img class="header-item-logo-img"
                            src="{% static 'img/python.png' %}" alt=""></a>
                </div>
                <div class="header-item-form">
                    <a href="{% url 'core:index' %}">
                        <h1>Py Commerce</h1>
                    </a>
                    <form>
                        <input type="text" id="search" name="search">
                    </form>
                    <ul class="header-item-form-categorias">
                        <a href="{% url 'products:product_list_by_category' 'smartphone' %}"><li>Smartphone</li></a>
                        <a href="{% url 'products:product_list_by_category' 'computador' %}"><li>Computador</li></a>
                        <a href="{% url 'products:product_list_by_category' 'eletronicos' %}"><li>Eletrônicos</li></a>
                        <a href="{% url 'products:product_list_by_category' 'acessorios' %}"><li>Acessórios</li></a>
                    </ul>
                </div>
                <div class="header-item-right">
                    <div class="header-item-right-meuspedidos">
                        <i class="fa-solid fa-gift"></i>
                        {% if request.user.is_authenticated %}
                            <a href="#meuspedidos"><span>Olá, {{user_authenticated|capfirst}} </span></a>
                        {% else %}
                            <a href="{% url 'accounts:login_user' %}"><span>{{user_authenticated|capfirst}}</span></a>
                        {% endif %}
                    </div>
                    <div>
                        <a href="#profile"><i class="fa-2x fa-sharp fa-solid fa-user"></i></a>
                        <a href="{% url 'cart:cart_detail' %}"><i class="fa-2x fa-sharp fa-solid fa-cart-shopping"></i></a>
                        <span class="fa-layers-counter">{{cart.get_quantity_products}}</span>
                    </div>
                    <div class="header-item-right-minhaconta">
                        <i class="fa-solid fa-gift"></i>
                        <a href="{% url 'perfil:my_perfil' %}"> <span>Minha conta</span></a>
                    </div>
                </div>
            </div>
        </div>
    </header>


    {% block content %}

        {% block js %} {% endblock %}

    {% endblock %}


</body>

</html>

templates/error404.html
<h1>ERROR</h1>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} index {% endblock %}

{% block content %}

<!-- <div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url 'core:index' %}">All</a>
        </li>
    </ul>
</div> -->
<!--
    TODO PAGINAÇÃO DOS ITEMS
-->
<div id="main" class="product-list-container">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    <div class="product-list-content">
        <!-- PAGINATION PREVIOUS -->
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"><i class="fa-solid fa-backward"></i></a>
        {% endif %}
        {% for obj in page_obj %}
        <div class="product-list-item">
            <a href="{{ obj.get_absolute_url }}">
                <div class="product-list-item-img">
                    <img src="{% if obj.image %}{{ obj.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
                </div>
                <div>
                    <a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a>
                </div>
                <br>
                ${{ obj.price }}
            </a>
        </div>
        {% endfor %}
        <!-- PAGINATION NEXT -->
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"><i class="fa-duotone fa-forward"></i></a>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% load static %}

{% block title %} index {% endblock %}

{% block content %}



<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{xd.as_p}}
    {% for x in user.image.all %}
    <img src="{{x}}" width="250" height="250">
    {% endfor %}
        
    <button type="submit"> Continuar </button>
</form>

{% endblock %}